server:
  port: 80
  servlet:
    context-path: /wx01

spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  redis:
    database: 0                           # Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0 redis\u670916\u4E2A\u5E93\uFF09
    host: 192.168.43.11                  # Redis\u670D\u52A1\u5668\u5730\u5740
    port: 6379                            # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    password: 123456                      # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    jedis:                                # spirngboot1.x\u4E0E2.x\u533A\u522B\u662F2.x\u6DFB\u52A0\u4E00\u4E2A\u524D\u7F00jedis\u30011.x\u6CA1\u6709
      pool:
        max-active: 100                  # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-idle: 10                     # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0                      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        max-wait: -1                     # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
    timeout:  5000                       # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09\uFF0C\u4E0D\u80FD\u8BBE\u7F6E\u4E3A0\uFF0C\u65F6\u95F4\u592A\u77ED\u8FDE\u63A5\u4E0D\u4E0A\u4F1A\u62A5\u9519
##  jpa:
##    database: mysql
##    show-sql: true
  freemarker:
    allow-request-override: false
    request-context-attribute:  req
    suffix: .ftl
    content-type: text/html;charset=UTF-8
    enabled:  true
    cache:  false
    template-loader-path: classpath:/templates/
    charset:  UTF-8
#  devtools:
#    restart:
#      enabled:  true                       #\u70ED\u90E8\u7F72\u751F\u6548
#      exclude:  WEB-INF/**                 #classpath\u76EE\u5F55\u4E0B\u7684WEB-INF\u6587\u4EF6\u5939\u5185\u5BB9\u4FEE\u6539\u4E0D\u91CD\u542F
#      additional-paths: src/main/java     #\u8BBE\u7F6E\u91CD\u542F\u7684\u76EE\u5F55
#
#
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xy.wx01.model





